contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #scscape channel"
    url: https://nfcore.slack.com/channels/scscape
    about: Discussion about the nf-core/scscape pipeline
